# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\kmol\scarysim-master\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalSliderYaw = QtWidgets.QSlider(self.centralWidget)
        self.horizontalSliderYaw.setGeometry(QtCore.QRect(340, 530, 641, 21))
        self.horizontalSliderYaw.setMinimum(-180)
        self.horizontalSliderYaw.setMaximum(180)
        self.horizontalSliderYaw.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderYaw.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.horizontalSliderYaw.setTickInterval(10)
        self.horizontalSliderYaw.setObjectName("horizontalSliderYaw")
        self.verticalSliderPitch = QtWidgets.QSlider(self.centralWidget)
        self.verticalSliderPitch.setGeometry(QtCore.QRect(300, 30, 21, 481))
        self.verticalSliderPitch.setMinimum(-90)
        self.verticalSliderPitch.setMaximum(90)
        self.verticalSliderPitch.setProperty("value", 30)
        self.verticalSliderPitch.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderPitch.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSliderPitch.setTickInterval(10)
        self.verticalSliderPitch.setObjectName("verticalSliderPitch")
        self.groupBoxSimple = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxSimple.setGeometry(QtCore.QRect(20, 130, 251, 141))
        self.groupBoxSimple.setObjectName("groupBoxSimple")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxSimple)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 211, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSliderTh1 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTh1.setMinimum(-180)
        self.horizontalSliderTh1.setMaximum(180)
        self.horizontalSliderTh1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTh1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderTh1.setTickInterval(10)
        self.horizontalSliderTh1.setObjectName("horizontalSliderTh1")
        self.gridLayout.addWidget(self.horizontalSliderTh1, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.horizontalSliderTh2 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderTh2.setMinimum(-180)
        self.horizontalSliderTh2.setMaximum(180)
        self.horizontalSliderTh2.setProperty("value", 90)
        self.horizontalSliderTh2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderTh2.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderTh2.setTickInterval(10)
        self.horizontalSliderTh2.setObjectName("horizontalSliderTh2")
        self.gridLayout.addWidget(self.horizontalSliderTh2, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.horizontalSliderZ = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderZ.setMaximum(50)
        self.horizontalSliderZ.setTracking(True)
        self.horizontalSliderZ.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderZ.setInvertedAppearance(False)
        self.horizontalSliderZ.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderZ.setTickInterval(5)
        self.horizontalSliderZ.setObjectName("horizontalSliderZ")
        self.gridLayout.addWidget(self.horizontalSliderZ, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 410, 251, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(131, 21, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(131, 46, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(131, 71, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.labelZ = QtWidgets.QLabel(self.groupBox_2)
        self.labelZ.setGeometry(QtCore.QRect(179, 71, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelZ.setFont(font)
        self.labelZ.setObjectName("labelZ")
        self.labelY = QtWidgets.QLabel(self.groupBox_2)
        self.labelY.setGeometry(QtCore.QRect(179, 46, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelY.setFont(font)
        self.labelY.setObjectName("labelY")
        self.labelX = QtWidgets.QLabel(self.groupBox_2)
        self.labelX.setGeometry(QtCore.QRect(179, 21, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelX.setFont(font)
        self.labelX.setObjectName("labelX")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(21, 21, 22, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.labelThZ = QtWidgets.QLabel(self.groupBox_2)
        self.labelThZ.setGeometry(QtCore.QRect(69, 71, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelThZ.setFont(font)
        self.labelThZ.setObjectName("labelThZ")
        self.labelTh1 = QtWidgets.QLabel(self.groupBox_2)
        self.labelTh1.setGeometry(QtCore.QRect(69, 21, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelTh1.setFont(font)
        self.labelTh1.setObjectName("labelTh1")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(21, 46, 22, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(21, 71, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.labelTh2 = QtWidgets.QLabel(self.groupBox_2)
        self.labelTh2.setGeometry(QtCore.QRect(69, 46, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelTh2.setFont(font)
        self.labelTh2.setObjectName("labelTh2")
        self.groupBoxTarget = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBoxTarget.setEnabled(False)
        self.groupBoxTarget.setGeometry(QtCore.QRect(20, 280, 251, 121))
        self.groupBoxTarget.setObjectName("groupBoxTarget")
        self.lineEditTx = QtWidgets.QLineEdit(self.groupBoxTarget)
        self.lineEditTx.setGeometry(QtCore.QRect(50, 20, 113, 20))
        self.lineEditTx.setObjectName("lineEditTx")
        self.lineEditTy = QtWidgets.QLineEdit(self.groupBoxTarget)
        self.lineEditTy.setGeometry(QtCore.QRect(50, 50, 113, 20))
        self.lineEditTy.setObjectName("lineEditTy")
        self.commandLinkButtonGo = QtWidgets.QCommandLinkButton(self.groupBoxTarget)
        self.commandLinkButtonGo.setGeometry(QtCore.QRect(170, 40, 61, 41))
        self.commandLinkButtonGo.setObjectName("commandLinkButtonGo")
        self.label_9 = QtWidgets.QLabel(self.groupBoxTarget)
        self.label_9.setGeometry(QtCore.QRect(20, 50, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(self.groupBoxTarget)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBoxTarget)
        self.label_8.setGeometry(QtCore.QRect(20, 25, 16, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEditTz = QtWidgets.QLineEdit(self.groupBoxTarget)
        self.lineEditTz.setGeometry(QtCore.QRect(50, 80, 113, 20))
        self.lineEditTz.setObjectName("lineEditTz")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 30, 251, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButtonSimple = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonSimple.setGeometry(QtCore.QRect(20, 20, 101, 17))
        self.radioButtonSimple.setChecked(True)
        self.radioButtonSimple.setObjectName("radioButtonSimple")
        self.radioButtonTarget = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButtonTarget.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.radioButtonTarget.setObjectName("radioButtonTarget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(330, 20, 661, 501))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ScarySim"))
        self.horizontalSliderYaw.setToolTip(_translate("MainWindow", "Yaw"))
        self.verticalSliderPitch.setToolTip(_translate("MainWindow", "Pitch"))
        self.groupBoxSimple.setTitle(_translate("MainWindow", "Simple steering"))
        self.label_2.setText(_translate("MainWindow", "Th2"))
        self.label_3.setText(_translate("MainWindow", "z"))
        self.label.setText(_translate("MainWindow", "Th1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Position"))
        self.label_4.setText(_translate("MainWindow", "X"))
        self.label_5.setText(_translate("MainWindow", "Y"))
        self.label_6.setText(_translate("MainWindow", "Z"))
        self.labelZ.setText(_translate("MainWindow", "X"))
        self.labelY.setText(_translate("MainWindow", "X"))
        self.labelX.setText(_translate("MainWindow", "X"))
        self.label_10.setText(_translate("MainWindow", "Θ1"))
        self.labelThZ.setText(_translate("MainWindow", "X"))
        self.labelTh1.setText(_translate("MainWindow", "X"))
        self.label_11.setText(_translate("MainWindow", "Θ2"))
        self.label_12.setText(_translate("MainWindow", "Z"))
        self.labelTh2.setText(_translate("MainWindow", "X"))
        self.groupBoxTarget.setTitle(_translate("MainWindow", "Target"))
        self.lineEditTx.setText(_translate("MainWindow", "1.0"))
        self.lineEditTy.setText(_translate("MainWindow", "1.0"))
        self.commandLinkButtonGo.setText(_translate("MainWindow", "GO"))
        self.label_9.setText(_translate("MainWindow", "Y"))
        self.label_7.setText(_translate("MainWindow", "Z"))
        self.label_8.setText(_translate("MainWindow", "X"))
        self.lineEditTz.setText(_translate("MainWindow", "0.0"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Mode"))
        self.radioButtonSimple.setText(_translate("MainWindow", "Simple steering"))
        self.radioButtonTarget.setText(_translate("MainWindow", "Target steering"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

